/**
 * The build-time listing of `samples/`, generated by the `zpcrweb-samples` plugin in
 * `vite.config.ts`. Declared here because tsc cannot see a module that only exists inside the
 * bundler; `lib/samples.ts` is the only thing that imports it.
 */
declare module "virtual:samples" {
  export const SAMPLE_FILES: { name: string; size: number; lastModified: number }[];
}
