/**
 * What a file's content says, reduced to a small record that can be cached in IndexedDB — the
 * bridge between "this file is loaded and decoded" and "the Files table can describe a thousand
 * files it has never opened".
 *
 * The app decodes a file **only** as part of loading it (see `apps/web/ARCHITECTURE.md`, "Files,
 * loaded files, and the one selection"). That single rule is what keeps a large catalog cheap,
 * and it is only affordable because of this module: at the one moment the run *is* decoded, this
 * takes everything the file list will ever want to say about it — name, run date, protocol, plate,
 * targets, samples, read count, state — and hands it to `db.ts`'s `putSummary`. Nothing else ever
 * needs the archive again to draw a row.
 *
 * Every field is therefore derived, never authoritative: a summary can be thrown away and
 * regenerated by loading the file, and is refreshed on every load, so an edit that changes what
 * the file says (a rename, an attached plate) updates the row as a matter of course.
 */
import { plateTargets, runCompleteness, runProgressFromNames } from "@zpcrweb/core";
import type { FileSummary } from "../state/db";
import type { LoadedFile, PlateFileResult, RunResult } from "../state/useZpcrStore";
import { experimentIdentity, isPendingExperiment } from "./experiment";
import { plateDisplayName } from "./plateNames";
import { plateFileEncryptionStatus, runEncryptionStatus } from "./encryptionStatus";

/**
 * Summarize one loaded file. `storedName` is the app's live experiment name (the same value
 * `experimentIdentity` takes), so a name typed a moment ago is what gets cached rather than the
 * archive's not-yet-rewritten copy.
 *
 * A file that hasn't decoded — an encrypted `.pcrd` with no password yet — still gets a summary:
 * its name (from the file name), its `locked` encryption status, and nulls for everything that
 * needed the plaintext. That is a truthful row, and it is replaced the moment the password lands
 * and the file re-parses.
 */
export function summarizeFile(
  file: LoadedFile,
  run: RunResult | undefined,
  plateFile: PlateFileResult | undefined,
  password: string,
  storedName: string | undefined,
): FileSummary {
  const identity = experimentIdentity(file, run, storedName);
  const zpcr = run?.zpcr ?? null;
  const plate = plateFile
    ? plateFile.plate
    : zpcr?.plates(password || undefined)[0]?.pltd.plate ?? null;
  return {
    name: identity.name,
    named: identity.named,
    dateMs: identity.date?.getTime() ?? null,
    protocol: zpcr?.protocol()?.name || null,
    plate: plate ? plateDisplayName(plate) : null,
    targets: plate ? plateTargets(plate) : [],
    samples: plate?.samples ?? [],
    reads: zpcr ? zpcr.reads.length : null,
    wells: plateFile?.plate ? plateFile.plate.wells.filter((w) => w.loaded).length : null,
    state: runState(file, run),
    encryption: (plateFile
      ? plateFileEncryptionStatus(plateFile, password)
      : runEncryptionStatus(run, password)
    ).kind,
  };
}

/**
 * Where a run stands, as one value — the same three distinctions the file bar's chips draw
 * (`useZpcrStore`'s `pendingIds`/`inProgressIds`/`incompleteIds`), collapsed here because a table
 * row shows one word and a file can only be in one of these states.
 */
function runState(file: LoadedFile, run: RunResult | undefined): FileSummary["state"] {
  const zpcr = run?.zpcr;
  if (!zpcr) return "none";
  if (isPendingExperiment(file.kind, zpcr)) return "pending";
  if (runProgressFromNames(zpcr.archive.entries).inProgress) return "running";
  if (runCompleteness(zpcr).incomplete) return "incomplete";
  // A standalone plate or protocol file is a run in no sense at all; only a file that decoded to
  // something with reads has actually completed one.
  return zpcr.reads.length > 0 ? "complete" : "none";
}
