/**
 * The sample files shipped with the app — the `samples` folder at the bottom of the Files view,
 * and the run the welcome screen offers.
 *
 * **Nothing here is a list.** `virtual:samples` is generated by `vite.config.ts` from a read of
 * the repo's `samples/` directory at build time, so a file added to (or removed from) that
 * directory shows up in (or leaves) the app on the next build with no source change anywhere.
 * The same plugin serves the bytes at `/examples/<name>`, which is what {@link sampleUrl} builds.
 *
 * A sample is opened by URL, through the same fetch → `addFiles` path a `#load=` link uses, so
 * what the app ends up holding is an ordinary copy of the file: editable, downloadable, closable,
 * and with the samples folder's own row ticked while it is open. They are read-only in the sense
 * that matters — an edit is never written back to the bundled copy — which is the one way they
 * differ from a granted folder on disk.
 */
import { SAMPLE_FILES } from "virtual:samples";

/** One bundled sample, as the folder pane lists it. Shaped like `diskFolders.ts`'s `DiskEntry`
 * file rows on purpose: the same component draws both. */
export interface SampleFile {
  name: string;
  size: number;
  /** The file's mtime in the repo, epoch ms — the same thing a disk row shows. */
  lastModified: number;
}

/** The folder's name in the Files view, and nothing else: a sample opens under its own file name,
 * not a folder-rooted path, because the app holds a copy rather than the file itself. */
export const SAMPLES_LABEL = "samples";

/** Every bundled sample, sorted by name. Empty is a legitimate state (a checkout with no
 * `samples/`), and the folder simply says it has nothing in it. */
export const SAMPLE_FILES_LIST: readonly SampleFile[] = SAMPLE_FILES;

/**
 * Where one sample's bytes live. Relative to the page, so it resolves on a dev server, on a
 * subpath deploy and offline-cached alike; the name is escaped because sample names contain
 * spaces (`QuickPlate_96 wells_All Channels.pltd`).
 */
export function sampleUrl(name: string): string {
  return `examples/${encodeURIComponent(name)}`;
}
